name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend image
        run: |
          docker build -t sriganesh737/mind-meld-react-frontend:latest ./frontend
          docker push sriganesh737/mind-meld-react-frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t sriganesh737/mind-meld-react-backend:latest ./backend
          docker push sriganesh737/mind-meld-react-backend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull images from docker hub
        run: |
          docker pull sriganesh737/mind-meld-react-frontend:latest
          docker pull sriganesh737/mind-meld-react-backend:latest
      
      - name: Delete old containers
        run: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)

      - name: Run new containers
        run: |
          docker run -d -p 3000:80 sriganesh737/mind-meld-react-frontend:latest
          docker run -d -p 8000:8000 sriganesh737/mind-meld-react-backend:latest