name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push frontend image
        run: |
          docker build -t sriganesh737/mind-meld-react-frontend:latest ./frontend
          docker push sriganesh737/mind-meld-react-frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t sriganesh737/mind-meld-react-backend:latest ./backend
          docker push sriganesh737/mind-meld-react-backend:latest
